const sportsArray = {
  Soccer: {
    FIFAWorldCup: 'fifaworldcup',
    UEFAChampionsLeague: 'uefachampionsleague',
    EnglishPremierLeague: 'premierleague',
    FACup: 'facup',
    CarabaoCup: 'carabaocup',
    LaLiga: 'laliga',
    CopaDeyRey: 'copadelrey',
    SerieA: 'seriea',
    Bundesliga: 'bundesliga',
    UefaEuropaLeague: 'uefaeuropaleague',
    CopaLibertadores: 'copalibertadores',
    AfricaCupOfNations: 'africacupofnations',
    AsianCup: 'asiacup',
  },
  Cricket: {
    ICCCricketWorldCup: 'cricketworldcup',
    IndianPremierLeague: 'ipl',
    TheAshes: 'theashes',
    PakistanSuperLeague: 'psl',
  },
  Basketball: {
    NBA: 'nba',
    FIBABasketballWorldCup: 'fibaworldcup',
    EuroLeague: 'euroleague',
    LigaACB: 'ligaacb',
    ChineseBasketballAssociation: 'cba',
  },
  Tennis: {
    Wimbledon: 'wimbledon',
    USOpen: 'usopen',
    AustralianOpen: 'australianopen',
    FrenchOpen: 'frenchopen',
    ATPWorldTourFinals: 'atpworldtourfinals',
    WTAFinals: 'wtafinals',
  },
  Volleyball: {
    FIVBVolleyballWorldChampionships: 'fivbworldchampionships',
    OlympicsVolleyball: 'olympicsvolleyball',
    ItalianVolleyballLeague: 'seriea1',
    BrazilVolleyballLeague: 'superliga',
    RussianVolleyballLeague: 'superliga',
  },
  Baseball: {
    MajorLeagueBaseball: 'mlb',
    WorldSeries: 'worldseries',
    CaribbeanSeries: 'caribbeanseries',
    JapanSeries: 'japanseries',
    KoreanBaseballOrganization: 'kbo',
  },
  Rugby: {
    RugbyWorldCup: 'rugbyworldcup',
    SixNationsChampionship: 'sixnationschampionship',
    RugbyChampionship: 'rugbychampionship',
    PremiershipRugby: 'premiershiprugby',
    Top14: 'top14',
  },
};

export default sportsArray;
